"""add economic_activity and ciiu_code to clients

Revision ID: 54e590e6494f
Revises: 0003
Create Date: 2026-07-06 15:29:40.496320

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54e590e6494f'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('economic_activity', sa.String(length=50), nullable=False, server_default=''))
    op.add_column('clients', sa.Column('ciiu_code', sa.String(length=10), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'ciiu_code')
    op.drop_column('clients', 'economic_activity')
    # ### end Alembic commands ###
