"""add is_credit_note to supplier_invoices

Revision ID: fb3058618fff
Revises: 54e590e6494f
Create Date: 2026-07-06 19:30:19.204221

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb3058618fff'
down_revision: Union[str, None] = '54e590e6494f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplier_invoices', sa.Column('is_credit_note', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supplier_invoices', 'is_credit_note')
    # ### end Alembic commands ###
